services:
  app:
    build: .
    image: backend
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app

  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: backend
    healthcheck:
      test: pg_isready -U backend
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 2s

volumes:
  postgres:
