# Generated by Django 5.0.4 on 2024-04-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_item_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='owner',
            new_name='list',
        ),
    ]
